# Generated by Django 5.1 on 2024-08-21 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='main.product'),
        ),
    ]
