# Generated by Django 5.1 on 2024-08-21 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_comment_com_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='main.product'),
        ),
    ]
