# Generated by Django 5.1 on 2024-08-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_comment_com_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_rate',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
