# Generated by Django 5.1 on 2024-08-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_comment_com_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_rate',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
    ]
