# Generated by Django 5.1 on 2024-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_property_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
