# Generated by Django 5.1 on 2024-08-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_product_product_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_amenities',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_beth_patch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
