# Generated by Django 5.1 on 2024-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
