# Generated by Django 5.1 on 2024-09-18 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=20)),
                ('com_email', models.EmailField(max_length=40)),
                ('com_message', models.CharField(max_length=300)),
                ('com_created', models.DateField(auto_now_add=True)),
                ('com_rate', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_image', models.FileField(blank=True, null=True, upload_to='wish_image', verbose_name='Wish Image')),
                ('wish_name', models.CharField(blank=True, max_length=20, verbose_name='Wish Name')),
                ('wish_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wish_status', models.CharField(choices=[('in_stock', 'In Stock'), ('coming_soon', 'Coming Soon')], default='coming_soon', max_length=20, verbose_name='Wish Status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_total', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
                ('wishlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wishlist')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='wishlist_products',
            field=models.ManyToManyField(related_name='carts', through='main.CartItem', to='main.wishlist'),
        ),
    ]
