# Generated by Django 5.1 on 2024-08-29 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=20)),
                ('com_email', models.EmailField(max_length=40)),
                ('com_message', models.CharField(max_length=300)),
                ('com_created', models.DateField(auto_now_add=True)),
                ('com_rate', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.product')),
            ],
        ),
    ]
