# Generated by Django 5.1 on 2024-09-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
