# Generated by Django 5.1 on 2024-09-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cart_ship_hand_alter_cart_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_name', models.CharField(blank=True, max_length=20, null=True)),
                ('per_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('per_number', models.IntegerField(blank=True, default=0, null=True)),
                ('per_service_type', models.CharField(blank=True, max_length=20, null=True)),
                ('per_country', models.CharField(blank=True, max_length=20, null=True)),
                ('per_house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('per_apartment', models.CharField(blank=True, max_length=20, null=True)),
                ('per_town', models.CharField(blank=True, max_length=20, null=True)),
                ('per_city', models.CharField(blank=True, max_length=20, null=True)),
                ('per_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('per_notes', models.TextField(blank=True, null=True)),
                ('per_payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('per_card_subtotal', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('per_ship_hand', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('per_order_total', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
