# Generated by Django 5.1 on 2024-09-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='per_vat',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
